# -*- coding: utf-8 -*-
"""All step from 1 to 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eA3WpjdAIBbTwBBbhIWQtg1H44kup2u2
"""

! pip install tiktoken

import torch
from torch.utils.data import DataLoader,Dataset

import tiktoken
with open("the-verdict.txt","r") as f:
  raw_text=f.read()
tokenizer=tiktoken.get_encoding("gpt2")

integer=tokenizer.encode(raw_text,allowed_special={"<|endoftext|>"})
print(type(integer)),integer

class GPT_2:
  def __init__(self,text,tokenizer,max_length,stride) :
    self.input_ids=[]
    self.target_ids=[]
    token=tokenizer.encode(text,allowed_special={"<|endoftext|>"})
    for i in range (0,len(token)-max_length,stride):
      input_txt=token[i:i+max_length]
      output_txt=token[i+1:i+max_length+1]
      self.input_ids.append(torch.tensor(input_txt))
      self.target_ids.append(torch.tensor(output_txt))


  def __len__(self):
      return len(self.target_ids)
  def __getitem__(self,idx):
      return self.input_ids[idx],self.target_ids[idx]

def create_dataloader(text,max_length=256,stride=128,batch_size=8,shuffle=False,num_workers=0,drop_last=True):
  tokenizer=tiktoken.get_encoding("gpt2")
  dataset=GPT_2(text,tokenizer,max_length,stride)
  dataloader=DataLoader(
      dataset,batch_size=batch_size,shuffle=shuffle,num_workers=num_workers
  )
  return dataloader



with open("the-verdict.txt","r") as f:
  raw_text=f.read()
dataloader=create_dataloader(raw_text,4,4,8,shuffle=False)
data_iter=iter(dataloader)
inputs,targets=next(data_iter)
data_iter

vocab_size=50257
output_dim=256
tokens_emned=torch.nn.Embedding(vocab_size,output_dim)
print("Token_IDS",inputs)
print(inputs.shape)

token_embedding=tokens_emned(inputs)
print(token_embedding.shape)

pos_embed=torch.nn.Embedding(4,output_dim)
pos_embedding=pos_embed(torch.arange(4))
print(pos_embedding.shape)

input_embedding=pos_embedding+token_embedding
print(input_embedding)