# -*- coding: utf-8 -*-
"""Self attention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15aOvtGGENmgKS-hmyqxIt_PoECCjm6re
"""

! pip3 install tiktoken
import matplotlib.pyplot as plt

import importlib
import tiktoken

from torch.utils.data import Dataset,DataLoader
import torch

class GPT(Dataset):
  def __init__(self,txt,tokenizer,max_length,stride):
    self.input_ids=[]
    self.target_ids=[]
    token_ids=tokenizer.encode(txt,allowed_special={"<|endoftext|>"})
    for i in range(0,len(token_ids)-max_length,stride):
      input_chunk=token_ids[i:i+max_length]
      target_chunk=token_ids[i+1:i+max_length+1]
      self.input_ids.append(torch.tensor(input_chunk))
      self.target_ids.append(torch.tensor(target_chunk))
  def __len__(self):
    return len(self.input_ids)
  def  __getitem__(self,idx):
    return self.input_ids[idx],self.target_ids[idx]

def create_dataloader(txt,batch_size=4,max_length=256,stride=128,shuffle=True,drop_last=True,num_workers=0):
  tokenizer=tiktoken.get_encoding("gpt2")
  dataset=GPT(txt,tokenizer,max_length,stride)
  dataloader=DataLoader(
      dataset,
      batch_size=batch_size,
      shuffle=shuffle,
      drop_last=False,
      num_workers=num_workers

  )
  return dataloader

with open("the-verdict.txt","r") as f:
  raw_text=f.read()

vocab_size=50257
output_dim=3
token_embedding=torch.nn.Embedding(vocab_size,output_dim)
txt=("Your journey starts with one step")

max_length=3
dataloader=create_dataloader(
    txt,batch_size=6,max_length=max_length,
    stride=1,shuffle=False
)
data_iter=iter(dataloader)
inputs,targets=next(data_iter)

print("Token_IDS",inputs)
print(inputs.shape)

token_embeddings=token_embedding(inputs)
print(token_embeddings.shape)

context_length=max_length
pos=torch.nn.Embedding(max_length,output_dim)

pos_embedding=pos(torch.arange(max_length))
pos_embedding = pos_embedding.unsqueeze(0)
pos_embedding.shape

input_embedd=token_embeddings+pos_embedding
print(input_embedd),input_embedd.shape







inp=torch.tensor(
   [ [0.43,0.15,0.89],
    [0.55,0.87,0.66],
    [0.57,0.85,0.64],
    [0.22,0.58,0.33],
    [0.77,0.25,0.10],
    [0.05,0.80,0.55]]
)



x_2 = inp[1] #A
d_in = inp.shape[1] #B
d_out = 2 #C

torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)
keys = inp @ W_key
values = inp @ W_value
queries = inp @ W_query
print("keys.shape:", keys.shape)

print("values.shape:", values.shape)

print("queries.shape:", queries.shape)

key_2=keys[1]
attn_score_2=query_2.dot(key_2)
attn_score_2

attn_scores_2=query_2 @ keys.T
attn_scores_2

attn_scores=queries @ keys.T
attn_scores

d_k=keys.shape[-1]
attn_weight_2=torch.softmax(attn_scores_2/d_k**0.5,dim=-1)
attn_weight_2

attn_weights=torch.softmax(attn_scores/d_k**0.5,dim=-1)
attn_weights

print(values)

context_vector=attn_weights @ values
context_vector

import torch.nn as nn

class SelfAttention_v1(nn.Module):

    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        keys = x @ self.W_key
        queries = x @ self.W_query
        values = x @ self.W_value

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )

        context_vec = attn_weights @ values
        return context_vec

torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inp))

class SelfAttention_v2(nn.Module):

    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)

        context_vec = attn_weights @ values
        return context_vec

torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inp))

"""# Casual Self Attention

"""

queries=sa_v2.W_query(inp)
keys=sa_v2.W_key(inp)
attn_scores=queries @ keys.T
attn_weights=torch.softmax(attn_scores/keys.shape[-1]**0.5,dim=1)
print(attn_weights)

context_length=attn_scores.shape[0]
mask_simple=torch.tril(torch.ones(context_length,context_length))
print(mask_simple)

masked_simple=attn_weights * mask_simple
print(masked_simple)

row_sums=masked_simple.sum(dim=1,keepdim=True)
masked_simple_norm=masked_simple/row_sums
print(masked_simple_norm)

print(attn_scores)

mask=torch.triu(torch.ones(context_length,context_length),diagonal=1)
masked=attn_scores.masked_fill(mask.bool(),-torch.inf)
print(masked)

attn_weights=torch.softmax(masked/keys.shape[-1]**0.5,dim=1)

print(attn_weights)

"""# With Dropouts"""

torch.manual_seed(123)
dropout=torch.nn.Dropout(0.5)
example=torch.ones(6,6)
print(dropout(example))

torch.manual_seed(123)
print(dropout(attn_weights))

batch=torch.stack((inp,inp),dim=0)
print(batch.shape)

class CausalAttention(nn.Module):

    def __init__(self, d_in, d_out, context_length,
                 dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout) # New
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New

    def forward(self, x):
        b, num_tokens, d_in = x.shape # New batch dimension b
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) # Changed transpose
        attn_scores.masked_fill_(  # New, _ ops are in-place
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)  # `:num_tokens` to account for cases where the number of tokens in the batch is smaller than the supported context_size
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights) # New

        context_vec = attn_weights @ values
        return context_vec

torch.manual_seed(123)
context_length=batch.shape[1]
ca=CausalAttention(d_in,d_out,context_length,0.0)
context_vec=ca(batch)
print(context_vec,context_vec.shape)

"""# Multi Head Attention Wrappper"""

class MultiHeadAttentionWrapper(nn.Module):
  def __init__(self,d_in,d_out,context_length,dropout,num_heads,qkv_bias=False):
    super().__init__()
    self.heads=nn.ModuleList(
        [CausalAttention(d_in,d_out,context_length,dropout,qkv_bias)
        for _ in range(num_heads)]
    )
  def forward(self,x):
    return torch.cat([head(x) for head in self.heads],dim=-1)

torch.manual_seed(123)
context_length=batch.shape[1]
d_in,d_out=3,2
mha=MultiHeadAttentionWrapper(d_in,d_out,context_length,0.0,num_heads=2)
context_vecs=mha(batch)
print(context_vecs,context_vecs.shape)