# -*- coding: utf-8 -*-
"""Byte pair

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFj4fJBPhSqplgZTePan5FX9g_YhxdIT

# BYTE PAIR TOKENIZATION
"""

! pip3 install tiktoken

import importlib
import tiktoken
print(importlib.metadata.version("tiktoken"))

tokenizer=tiktoken.get_encoding("gpt2")

text=(
    "Hello ,do you know who I am I am saksham <?endoftext|> "
    "From gwalior ,Ya! from gwalior"
)
integers=tokenizer.encode(text,allowed_special={"<|endoftext|>"})
print(integers)

strings=tokenizer.decode(integers)
print(strings)

print(tokenizer.decode([3415]))